// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repository

import (
	"context"
)

const findSomethingById = `-- name: FindSomethingById :one
SELECT id, name, created_at, updated_at
  FROM something
 WHERE id = $1
`

func (q *Queries) FindSomethingById(ctx context.Context, id int64) (Something, error) {
	row := q.db.QueryRow(ctx, findSomethingById, id)
	var i Something
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSomething = `-- name: ListSomething :many
SELECT id, name, created_at, updated_at
  FROM something
`

func (q *Queries) ListSomething(ctx context.Context) ([]Something, error) {
	rows, err := q.db.Query(ctx, listSomething)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Something
	for rows.Next() {
		var i Something
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
