// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"
)

type Querier interface {
	FindSomethingById(ctx context.Context, id int64) (Something, error)
	ListSomething(ctx context.Context) ([]Something, error)
}

var _ Querier = (*Queries)(nil)
